# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'zoyeal'

google-ID: 'UA-98053258-1'

menu:
- {name: '博文', folder: 'pages', file: 'posts.html'}
- {name: '相片', folder: 'pages', file: 'photos.html'}
- {name: '收藏', folder: 'pages', file: 'resources.html'}
- {name: '关于我', folder: 'pages', file: 'about.html'}
- {name: 'FUN', folder: 'pages', file: 'fun.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'weibo', link: 'https://weibo.com/zoyeal'}
- {icon: 'github', link: 'https://github.com/zoyeal'}
- {icon: 'instagram', link: 'https://instagram.com/dcdeng'}
- {icon: 'envelope', link: 'mailto:zoyeal@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: '后页'
  previous_page: '前页'

sharing_button_prompt: '分享至 ↷'

related_posts: '☟ 推荐阅读 . . .'

post_date_prefix: '✎  '
